### ISSUE TITLE
Numpy TypeError

### ISSUE THREAD

**Issue by ikcede** [absalon-james/velopyraptor#1]
I tried running your example code, and I got an error:
File "raptortest.py", line 14, in <module>
    encoder = Encoder(k, source)
  File "...velopyraptor/encoder.py", line 35, in **init**
    self.calculate_i_symbols()
  File "...velopyraptor/raptor.py", line 329, in calculate_i_symbols
    numpy.bitwise_xor(D[target_row], D[xor_row], D[target_row])
TypeError: return arrays must be of ArrayType

It seems that the third argument of numpy.bitwise_xor has to be an ndarray, but it returns an arraylike element, which the first two arguments are. 

This fixed the bug for me:
D[target_row] = numpy.bitwise_xor(D[target_row], D[xor_row])

(It may be because I'm running the latest numpy from Pip though.)

**Comment by absalon-james** [comment]
Thanks for the helpful information and sorry for the trouble.
What version of numpy are you using?  I am using 1,7,1.

My intentions with the third argument were to xor directly into D[target_row] rather than create a new ndarray.

EDIT:
It has come to my attention that my README was quite out of date.  Originally source was passed to the encoder/decoder as bitarrays.  This has been changed to numpy arrays to permit packing more bytes into each XOR operation at a time.  If it would be beneficial I can look into providing a helper class or maybe modifying my chunker to take data from a string instead of a file.

**Comment by ikcede** [comment]
I'm using Python 2.7.2 and Numpy 1.7.1.
Would it work either way with that fix? 

And that's fine, I'm planning on looking at the file encoding/decoding portion of the code later anyways. Thanks for the code though! I've been trying to implement RaptorQ on Java, and your source has been extremely helpful.

**Comment by absalon-james** [comment]
It should work either way as long as your source symbols are being passed to the encoder/decoder as numpy arrays.

**Comment by absalon-james** [comment]
Updated the README to reflect usage of numpy arrays as the source symbols and provided an optional string chunker to ease conversion to numpy arrays.
